import React, { useEffect, useMemo, useRef, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { annuityPV, effectiveAnnualRate, formatMoney, fv, growingPerpetuityPV, npv, pv, realRate } from './finance.js';
import { introSections, introSources, lessons, modules, sources, sourceNote } from './data.js';
import pdfCatalog from './pdf-catalog.json';
import mediaCatalog from './media-catalog.json';
import './styles.css';

const Icon = ({name,size=18}) => {
  const paths = {book:<><path d="M4 5.5A3.5 3.5 0 0 1 7.5 2H11v16H7.5A3.5 3.5 0 0 0 4 21.5z"/><path d="M20 5.5A3.5 3.5 0 0 0 16.5 2H13v16h3.5a3.5 3.5 0 0 1 3.5 3.5z"/></>, search:<><circle cx="11" cy="11" r="7"/><path d="m20 20-4-4"/></>, source:<><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"/><path d="M14 2v6h6M8 13h8M8 17h6"/></>, check:<path d="m5 12 4 4L19 6"/>, note:<><path d="M4 4h16v14H8l-4 4z"/><path d="M8 9h8M8 13h6"/></>};
  return <svg className="icon" width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">{paths[name]}</svg>;
};

const Field = ({label,value,onChange,min=-Infinity,max=Infinity,step=1,suffix}) => <label className="field"><span>{label}</span><div><input type="number" value={value} onChange={e=>{const next=Number(e.target.value); if(Number.isFinite(next)) onChange(Math.min(max,Math.max(min,next)))}} min={Number.isFinite(min)?min:undefined} max={Number.isFinite(max)?max:undefined} step={step}/>{suffix && <em>{suffix}</em>}</div></label>;

function TimelineLab() {
  const [amount,setAmount] = useState(1000), [rate,setRate] = useState(10), [years,setYears] = useState(1), [mode,setMode] = useState('forward');
  const safeRate=Math.max(-99.9,Math.min(100,rate))/100, safeYears=Math.max(0,Math.min(40,years));
  const result = mode === 'forward' ? fv(amount,safeRate,safeYears) : pv(amount,safeRate,safeYears);
  return <section id="discounting" className="lab" aria-labelledby="lab-title">
    <div className="lab-head"><div><h2 id="lab-title">Move one cash flow</h2><p>Pick a direction, then change the amount, rate, or time.</p></div><div className="segmented"><button className={mode==='forward'?'active':''} onClick={()=>setMode('forward')}>Compound</button><button className={mode==='back'?'active':''} onClick={()=>setMode('back')}>Discount</button></div></div>
    <div className="controls"><Field label={mode==='forward'?'Today':'Future cash flow'} value={amount} onChange={setAmount} min={0} step={100} suffix="$"/><Field label="Annual rate" value={rate} onChange={setRate} min={-90} max={100} step={.5} suffix="%"/><Field label="Years" value={years} onChange={setYears} min={0} max={40}/></div>
    <div className={`timeline ${mode==='back'?'reverse':''}`}>
      <div className="node"><strong>{formatMoney(mode==='forward'?amount:result)}</strong><span>today</span></div>
      <div className="line"><span>{mode==='forward'?'×':'÷'} (1 + {safeRate.toFixed(3)})<sup>{safeYears}</sup></span></div>
      <div className="node"><strong>{formatMoney(mode==='forward'?result:amount)}</strong><span>year {years}</span></div>
    </div>
    <p className="formula">{mode==='forward' ? 'FV = PV(1 + r)ᵗ' : 'PV = CFₜ / (1 + r)ᵗ'} <span>·</span> {formatMoney(result,2)}</p>
  </section>;
}

function HintPractice({completed,onComplete}) {
  const [answer,setAnswer]=useState(''), [feedback,setFeedback]=useState(''), [hint,setHint]=useState(0);
  const submitAnswer=()=>{const parsed=Number(answer.replaceAll('$','').replaceAll(',','').trim()); const ok=Number.isFinite(parsed)&&Math.abs(parsed-19758.19)<=1; setFeedback(ok?'Correct. The positive NPV says the system adds value.':'Not yet. Use dollars and round to the nearest dollar (answers within $1 are accepted).'); if(ok) onComplete();};
  return <form className="practice" onSubmit={e=>{e.preventDefault();submitAnswer()}}><div className="section-label">Your turn</div><h2>Should Boston install the lighting system?</h2><p>The system costs $230,000 today and saves $90,000 at the end of each of the next three years. The certain annual rate is 4%. Enter the NPV.</p>
    <div className="answer-row"><label><span className="sr-only">Net present value in dollars</span><b>$</b><input value={answer} onChange={e=>setAnswer(e.target.value)} inputMode="decimal" placeholder="Your answer"/></label><button className="primary" type="submit">Check reasoning <span>→</span></button></div>
    {feedback && <p className={feedback.startsWith('Correct')?'success':'try'}>{feedback}</p>}
    <button className="hint-button" type="button" onClick={()=>setHint(Math.min(3,hint+1))}>Reveal {hint ? 'next ' : ''}hint</button>
    {hint>=1 && <div className="hint"><b>1</b> Draw the dated cash flows: −230,000 at t=0, then +90,000 at t=1, 2, and 3.</div>}
    {hint>=2 && <div className="hint"><b>2</b> Convert each saving to date 0: 90,000/1.04ᵗ.</div>}
    {hint>=3 && <div className="hint"><b>3</b> −230,000 + 86,538.46 + 83,210.06 + 80,009.67 ≈ $19,758.</div>}
    {completed && <span className="complete-mark"><Icon name="check"/> Practice completed</span>}
  </form>;
}

function IntroCheck({completed,onComplete}) {
  const questions=[
    {q:'Which task is valuation?',a:0,options:['Estimating what a factory’s future cash flows are worth','Choosing whether to buy the factory'],why:'Valuation measures alternatives. Management uses those valuations, together with an objective, to choose.'},
    {q:'Which is a stock variable?',a:1,options:['Revenue earned during a quarter','Cash held at the quarter-end date'],why:'A stock is measured at an instant; a flow is measured over an interval.'},
    {q:'A guaranteed $100 payment arrives next year rather than today. What creates the modeling problem?',a:0,options:['Time','Risk'],why:'The payment is guaranteed by assumption, so uncertainty is set aside. Its date differs, so time is the remaining issue.'},
    {q:'How should the six principles be used?',a:1,options:['As universal laws without exceptions','As organizing assumptions whose approximations and limits must be examined'],why:'The lecture uses them to build a tractable framework, then explicitly returns to their limitations.'}
  ];
  const [answers,setAnswers]=useState({});
  const correct=questions.filter((q,i)=>answers[i]===q.a).length;
  return <section className="intro-check"><div className="section-label">Check the distinctions</div><h2>Four ideas that should not blur together</h2>{questions.map((q,i)=><fieldset key={q.q}><legend><span>{i+1}</span>{q.q}</legend>{q.options.map((o,j)=><label key={o} className={answers[i]===j?(j===q.a?'chosen correct':'chosen wrong'):''}><input type="radio" name={`intro-${i}`} checked={answers[i]===j} onChange={()=>setAnswers(a=>({...a,[i]:j}))}/>{o}</label>)}{answers[i]!==undefined&&<p className={answers[i]===q.a?'success':'try'}>{answers[i]===q.a?'Correct. ':''}{q.why}</p>}</fieldset>)}<div className="check-summary"><strong>{correct} / 4 correct</strong><button className="primary" disabled={correct<4} onClick={onComplete}>{completed?'Understanding saved':'Save understanding check'}</button></div></section>;
}

function IntroLesson({progress,setProgress,onOpenSources,onNext}) {
  const [perspective,setPerspective]=useState('company'),[info,setInfo]=useState(0),[bid,setBid]=useState(45);const video=useRef(null);
  const flow=perspective==='company'?[['1','Raise cash from investors'],['2','Invest in real assets'],['3','Generate cash from operations'],['4','Reinvest cash'],['5','Return cash to investors']]:[['1','Borrow from financial institutions'],['2','Invest in real assets or skills'],['3','Generate cash through labor'],['4','Consume or reinvest'],['5','Invest in financial assets']];
  const seek=t=>{if(video.current){video.current.currentTime=t;video.current.play()}};
  return <main id="intro-purpose" className="paper lesson intro-lesson"><div className="lesson-kicker">Finance Theory I<br/><span>01 / Introduction and course overview</span></div><h1>Finance is a system of decisions</h1><p className="lede">Follow money through an economy, separate valuation from management, and learn why time and risk organize the rest of the course.</p>
    <section className="intro-definition"><div><span className="hand-note">A disciplined language</span><h2>Mathematics + money</h2><p>The lecture opens with a broad definition: finance applies systematic reasoning to transactions involving money. The mathematics can range from arithmetic to advanced models; the point is disciplined comparison, not complexity for its own sake.</p><p>A <b>real asset</b> is a productive resource, tangible or intangible. A <b>financial asset</b> is a claim on cash flows. Financial-market alternatives establish an opportunity cost: choosing one use of funds means giving up the return available on a comparable alternative.</p><a className="source-anchor" href="/sources/introduction.pdf#page=3" target="_blank">Source · slides 3–6 ↗</a></div><aside><b>Two fundamental tasks</b><strong>Value the alternatives.</strong><strong>Manage toward an objective.</strong><p>Objectives + valuations → decisions</p></aside></section>
    <section id="intro-system" className="system-section"><div className="section-label apricot">The financial system</div><h2>Four actors, connected by flows</h2><p>Households supply labor, consume, save, and borrow. Nonfinancial corporations invest and operate. Financial intermediaries transform and route funds. Capital markets let claims be issued and traded. Product and labor markets sit around this financial view, even though the lecture deliberately sets them outside its main four-part model.</p><div className="system-routes"><div className="actor">Households</div><div className="route-stack"><div><span>indirect flow ⇄</span><b>Financial intermediaries</b><span>⇄ funding</span></div><div><span>direct claims ⇄</span><b>Capital markets</b><span>⇄ securities</span></div></div><div className="actor">Nonfinancial<br/>corporations</div></div><p className="route-note">Funds can travel indirectly through intermediaries or directly through market claims; the actors have multiple connections rather than one mandatory route.</p><a className="source-anchor" href="/sources/introduction.pdf#page=4" target="_blank">Source · slide 4 ↗</a></section>
    <section id="intro-decisions" className="cash-paths"><div className="lab-head"><div><div className="section-label">Follow the cash</div><h2>One five-path pattern, two objectives</h2></div><div className="segmented"><button className={perspective==='company'?'active':''} onClick={()=>setPerspective('company')}>Company</button><button className={perspective==='household'?'active':''} onClick={()=>setPerspective('household')}>Household</button></div></div><div className="five-paths">{flow.map(([n,t])=><div key={n}><span>{n}</span><p>{t}</p></div>)}</div><p className="objective"><b>{perspective==='company'?'Course objective: create and maximize shareholder value.':'Course objective: maximize lifetime happiness or expected utility.'}</b> {perspective==='company'?'A firm can value two plants, then choose the one that contributes more to this objective.':'A household can value saving and consumption plans, then choose the plan that best fits its lifetime objective.'} These are the objectives used by the 2008 lecture’s model; later analysis can question or broaden them.</p><div className="stock-flow"><div><span>Stock</span><strong>A snapshot at one date</strong><p>Examples: cash balance, debt, assets, equity. The balance-sheet identity is Assets = Liabilities + Equity.</p></div><div><span>Flow</span><strong>Measured over an interval</strong><p>Examples: revenue, expenses, investment, payouts. Accounting income can differ from cash flow; later valuation follows actual cash flows.</p></div></div><a className="source-anchor" href="/sources/introduction.pdf#page=7" target="_blank">Source · slides 7–12 ↗</a></section>
    <section id="intro-information" className="auction"><div><div className="section-label apricot">Price-discovery experiment</div><h2>What would you bid?</h2><p>In the 2008 classroom auction, students faced a wrapped object whose contents they did not know. This adapted interaction pauses before the reveal so you can set a maximum bid.</p><label>Maximum bid <strong>{formatMoney(bid)}</strong><input type="range" min="0" max="175" value={bid} onChange={e=>setBid(Number(e.target.value))}/></label><div className="reveal-buttons"><button onClick={()=>setInfo(0)} className={info===0?'active':''}>Wrapped</button><button onClick={()=>setInfo(1)} className={info===1?'active':''}>Reveal</button></div></div><aside><span>Information available</span><strong>{info===0?'A wrapped mystery object':'A 4 GB iPod Nano'}</strong><p>{info===0?'How wide is the range of plausible values? What risk are you taking by bidding?':'The classroom auction cleared at $45. The lecturer reported a $149 retail price in 2008.'}</p>{info===1&&<div className="auction-result">Your bid is {formatMoney(Math.abs(bid-45))} {bid===45?'from':bid<45?'below':'above'} the observed classroom price and {formatMoney(Math.abs(bid-149))} {bid===149?'from':bid<149?'below':'above'} the reported 2008 retail price.</div>}</aside><p className="auction-note">The clearing price records an outcome under the participants’ information and incentives. It is evidence about value, but it is not automatically the same as a fully informed valuation.</p><a className="source-anchor" href="/sources/session-01-transcript.pdf#page=10" target="_blank">Source · transcript pp. 10–14 ↗</a></section>
    <section id="intro-principles" className="principles"><div className="section-label">Time and risk</div><div className="two-challenges"><div><span>01</span><h2>Time</h2><p>Cash now and cash later are different dated quantities. Present Value develops the conversion.</p></div><div><span>02</span><h2>Risk</h2><p>Unknown outcomes make valuation and management harder. Historical data, probability, and statistics provide partial tools.</p></div></div><h2>Six organizing principles</h2><p className="principle-note">The lecture asks students to use these as a simplifying framework, while warning that they are approximations whose limits return in the final lecture.</p><ol className="principle-list"><li>No systematic free lunch.</li><li>Other things equal, people prefer more money, earlier money, and less risk.</li><li>Agents act to further their own interests.</li><li>Market prices move to balance supply and demand.</li><li>Financial markets are adaptive and competitive.</li><li>Risk sharing and frictions drive financial innovation.</li></ol><a className="source-anchor" href="/sources/introduction.pdf#page=13" target="_blank">Source · slides 13–14 ↗</a></section>
    <section id="intro-roadmap" className="roadmap"><div className="section-label apricot">Course roadmap</div><h2>From the original four-part arc to twelve modules</h2><div className="roadmap-groups"><div><b>A · Introduction</b><span>01 Introduction</span><span>02 Present Value</span></div><div><b>B · Valuation</b><span>03 Fixed Income</span><span>04 Equities</span><span>05 Forwards & Futures</span><span>06 Options</span></div><div><b>C · Risk</b><span>07 Risk & Return</span><span>08 Portfolio Theory</span><span>09 CAPM & APT</span></div><div><b>D · Corporate Finance</b><span>10 Capital Budgeting</span><span>11 Efficient Markets</span><span>12 Course Summary</span></div></div><p className="historical-note">The lecture’s named people, market examples, course rules, and grading scheme describe MIT’s Fall 2008 offering. This local course uses their teaching substance without presenting those details as current facts or requirements.</p><a className="source-anchor" href="/sources/course-outline.pdf#page=1" target="_blank">Source · course outline pp. 1–2 ↗</a></section>
    <section className="study-method"><div className="section-label">Learn by doing</div><h2>Use the original study loop</h2><div className="study-steps"><div><span>1</span><b>Skim first</b><p>Preview the slides so the structure is familiar.</p></div><div><span>2</span><b>Annotate</b><p>Write what the slides leave implicit while you watch.</p></div><div><span>3</span><b>Review</b><p>Return after the lecture and explain the logic yourself.</p></div><div><span>4</span><b>Attempt</b><p>Work problems both with others and alone; ask questions when reasoning breaks.</p></div></div><p>Finance becomes usable through repeated application. The complete original problem bank remains available locally.</p><a className="source-anchor" href="/sources/problem-sets.pdf#page=1" target="_blank">Open original problem bank ↗</a> <a className="source-anchor" href="/sources/introduction.pdf#page=18" target="_blank">Source · slide 18 ↗</a></section>
    <IntroCheck completed={progress.introPractice} onComplete={()=>setProgress(p=>({...p,introPractice:true}))}/>
    <section className="video-block"><h2>Original lecture · Introduction</h2><p>Complete MIT OpenCourseWare session 1 with local captions. Chapter buttons seek to verified caption cue starts.</p><video ref={video} controls preload="metadata"><source src="/media/session-01.mp4" type="video/mp4"/><track kind="captions" src="/sources/session-01.vtt" srcLang="en" label="English" default/></video><div className="chapters">{[['Actors',1287.96],['Two tasks',1388.59],['Auction',1673.85],['Stock & flow',2342.56],['Cash paths',2528.33],['Principles',3064.02],['Study method',3853.42]].map(([n,t])=><button key={n} onClick={()=>seek(t)}>{n}</button>)}</div></section>
    <section className="historical-aside"><h2>A 2008 motivation, kept in context</h2><p>Lo contrasts James Simons, Warren Buffett, and Jack Welch to show that finance can use very different kinds of quantitative reasoning, from advanced mathematics to close reading of business accounts. Claims about their wealth, firms, and roles belong to the lecture’s 2008 context.</p></section>
    <div className="lesson-footer"><button onClick={onOpenSources}><Icon name="book"/> MIT source trail</button><span>Slides 2–20 · transcript pp. 1–24 · course outline pp. 1–2</span><button className="finish" onClick={()=>setProgress(p=>({...p,introLesson:true}))}>{progress.introLesson?<><Icon name="check"/> Lesson saved</>:'Mark lesson complete'}</button></div><button className="next-lesson" onClick={onNext}>Next: Present Value <span>→</span></button>
  </main>;
}

function Lesson({progress,setProgress,onOpenSources}) {
  const [openDepth,setOpenDepth]=useState(false);
  return <main id="cashflows" className="paper lesson">
    <div className="lesson-kicker">Finance Theory I<br/><span>02 / Present value · first learning pilot</span></div>
    <h1>The value of money over time</h1>
    <p className="lede">Cash flows at different dates are different “currencies.” Convert them to one date before you compare or add them.</p>
    <TimelineLab/>
    <section id="streams" className="worked"><div className="section-label apricot">Worked example</div><div className="steps">
      <div className="step"><span className="step-no">1</span><div><h3>Choose the numeraire date</h3><p>Use today, <i>t</i> = 0. This gives every cash flow the same unit: date-0 dollars.</p><div className="math">PV(CF<sub>t</sub>) = CF<sub>t</sub> / (1 + r)<sup>t</sup></div></div></div>
      <div className="step"><span className="step-no">2</span><div><h3>Add only after conversion</h3><p>Include the initial cost as CF₀. The NPV operator is additive across dated cash flows.</p><div className="math">NPV = CF₀ + Σ CF<sub>t</sub> / (1 + r)<sup>t</sup></div></div></div>
    </div></section>
    <section className="concept"><h2>Why the rate matters</h2><p>The rate determines the discount factor that converts money between dates. Here it is the opportunity cost of capital: the return on an equivalent market investment. A higher rate makes distant positive cash flows worth less today. With a term structure, each dated cash flow can have its own appropriate rate.</p><button className="text-button" onClick={()=>setOpenDepth(!openDepth)}>{openDepth?'Hide':'Show'} derivation</button>{openDepth&&<div className="depth"><p>If one dollar today becomes (1 + r) dollars in one period, then 1/(1 + r) dollars today must be equivalent to one dollar in one period. Repeat the conversion t times to obtain the discount factor (1 + r)<sup>−t</sup>. Linearity then lets us value a sequence one cash flow at a time.</p><p><b>Boundary:</b> the early lectures assume known cash-flow magnitudes, signs and timing; known conversion factors; and frictionless conversion. Taxes, changing term structures, currencies, forecasting, and risk later qualify the model.</p></div>}</section>
    <section className="video-block"><h2>Original lecture · Present Value I</h2><p>Session 2 from MIT OpenCourseWare, with local captions.</p><video controls preload="metadata"><source src="/media/session-02.mp4" type="video/mp4"/><track kind="captions" src="/sources/session-02.vtt" srcLang="en" label="English" default/></video></section>
    <HintPractice completed={progress.practice} onComplete={()=>setProgress(p=>({...p,practice:true}))}/>
    <section id="annuities" className="pattern-grid">
      <div><span className="mini-title">Ordinary annuity</span><div className="math">PV = C/r [1 − 1/(1+r)<sup>T</sup>]</div><p>Start with a perpetuity C/r and subtract the identical perpetuity that begins after T. Discount that delayed tail by (1+r)<sup>T</sup>. At 10%, twenty $100,000 end-of-year payments are worth {formatMoney(annuityPV(100000,.1,20))}. If r = 0, the limit is simply C × T.</p></div>
      <div><span className="mini-title">Growing perpetuity</span><div className="math">PV = C₁/(r − g)</div><p>The next payment is C₁; later payments grow at g. A finite value requires r &gt; g, so discounted terms shrink. The recitation scholarship begins today: $1m now plus a growing perpetuity from year 1 equals {formatMoney(1_000_000+growingPerpetuityPV(1_020_000,.05,.02))}.</p></div>
    </section>
    <section id="compounding" className="concept"><h2>APR is a quote; EAR is a one-year growth rate</h2><p>When an APR r is compounded n times, each period earns r/n and the year contains n growth steps. Therefore EAR = (1 + r/n)<sup>n</sup> − 1. The lecture’s daily-compounding example turns $10,000 at 6.75% APR into {formatMoney(fv(10000,.0675/365,365),2)} after one year, an EAR of {(effectiveAnnualRate(.0675,365)*100).toFixed(3)}%.</p><p>Match the rate period to the cash-flow period. Monthly loan payments use the monthly rate; annual cash flows use an effective annual rate.</p></section>
    <section id="inflation" className="consistency"><h2>Keep units consistent</h2><div className="equation-strip"><span>Nominal cash flows</span><strong>discounted at nominal rates</strong><span>⇄ same PV ⇄</span><span>Real cash flows</span><strong>discounted at real rates</strong></div><p>Use 1 + r<sub>real</sub> = (1 + r<sub>nominal</sub>)/(1 + inflation). With 5% nominal interest and 2% inflation, the real rate is {(realRate(.05,.02)*100).toFixed(2)}%. Never combine nominal cash flows with a real rate or vice versa.</p></section>
    <div className="lesson-footer"><button onClick={onOpenSources}><Icon name="book"/> MIT source trail</button><span>Slides 3–35 · Recitation 1</span><button className="finish" onClick={()=>setProgress(p=>({...p,lesson:true}))}>{progress.lesson?<><Icon name="check"/> Lesson saved</>:'Mark lesson complete'}</button></div>
  </main>;
}

function Modules({onOpen}) { return <main className="paper list-page"><header><p>Course map</p><h1>Finance Theory I</h1><p className="lede">All twelve modules link to preserved source slides. Introduction and Present Value now contain authored notebook lessons; the others remain source maps.</p></header><div className="module-list">{modules.map(m=>{const ready=m.number==='01'||m.number==='02';return <article key={m.number} className={ready?'ready':''}><span>{m.number}</span><div><h2>{m.title}</h2><p>{m.concept}</p><div className="module-links"><a href={m.pdf} target="_blank">Local slides</a><a href={m.ocw} target="_blank">MIT page</a><a href={m.video} target="_blank">Online video</a></div></div><div className="status">{ready?'Notebook lesson':'Source map'}</div>{ready&&<button onClick={()=>onOpen(m.number==='01'?'intro':'pv')}>Open →</button>}</article>})}</div></main> }

function Library() { const recordings=[...mediaCatalog.recordings].sort((a,b)=>(a.session||99)-(b.session||99)); return <main className="paper list-page"><header><p>Source library</p><h1>Original material stays within reach</h1><p className="lede">All 49 distinct PDFs and 21 verified recordings are available locally. The 35 Present Value problems remain in their original PDF; this milestone does not claim they have all been converted into interactive exercises.</p></header><div className="source-list">{sources.map(s=><a key={s.title} href={s.href} target="_blank"><Icon name="source"/><div><span>{s.kind}</span><h2>{s.title}</h2><p>{s.detail}</p></div><b>↗</b></a>)}</div><div className="source-list"><h2>Local recordings</h2>{recordings.map(r=><a key={r.name} href={r.path} target="_blank"><Icon name="source"/><div><span>{r.session?`Lecture ${String(r.session).padStart(2,'0')}`:'Instructor interview'}</span><h2>{r.segments?.map(s=>s.title).join(' · ')||'Instructor insights'}</h2><p>{Math.round(r.duration_seconds/60)} min · verified local MP4</p></div><b>↗</b></a>)}</div><div className="source-list"><h2>Complete PDF archive</h2>{pdfCatalog.map((s,i)=><a key={s.filename} href={`/sources/original/${s.filename}`} target="_blank"><Icon name="source"/><div><span>Original PDF {String(i+1).padStart(2,'0')}</span><h2>{s.title}</h2><p>{s.pages?`${s.pages} pages · `:''}{Math.round(s.bytes/1024)} KB</p></div><b>↗</b></a>)}</div><p className="attribution">{sourceNote}</p></main> }

function Notes({onClose,storageKey,title}) { const [text,setText]=useState(()=>localStorage.getItem(storageKey)??(storageKey==='finance-notes-pv'?localStorage.getItem('finance-notes')||'':'')); useEffect(()=>localStorage.setItem(storageKey,text),[text,storageKey]); return <aside className="drawer notes" role="dialog" aria-modal="true" aria-label={`${title} study notes`}><div className="drawer-head"><h2>{title} notes</h2><button onClick={onClose} aria-label="Close notes">×</button></div><p>Saved automatically for this lesson.</p><textarea autoFocus value={text} onChange={e=>setText(e.target.value)} placeholder="Write what changed your understanding…"/></aside> }
function SourceDrawer({open,onClose,items}) { if(!open)return null; return <aside className="drawer" role="dialog" aria-modal="true" aria-label="Lesson source trail"><div className="drawer-head"><h2>Source trail</h2><button onClick={onClose} aria-label="Close sources">×</button></div><p>Original MIT 15.401 materials used by this lesson.</p>{items.map(s=><a key={s.title} href={s.href} target="_blank"><span>{s.kind}</span>{s.title}<b>↗</b></a>)}</aside> }

function App(){
  const [view,setView]=useState('learn'), [sourcesOpen,setSourcesOpen]=useState(false), [notesOpen,setNotesOpen]=useState(false), [query,setQuery]=useState('');
  const [currentLesson,setCurrentLesson]=useState('intro');
  const [progress,setProgress]=useState(()=>{try{return JSON.parse(localStorage.getItem('finance-progress'))||{}}catch{return{}}});
  useEffect(()=>localStorage.setItem('finance-progress',JSON.stringify(progress)),[progress]);
  useEffect(()=>{const close=e=>{if(e.key==='Escape'){setSourcesOpen(false);setNotesOpen(false)}};window.addEventListener('keydown',close);return()=>window.removeEventListener('keydown',close)},[]);
  const results=useMemo(()=>query.trim()?([...introSections,...lessons,...modules].filter(x=>(x.title+' '+(x.summary||x.concept)).toLowerCase().includes(query.toLowerCase())).slice(0,8)):[],[query]);
  const openLesson=lesson=>{setCurrentLesson(lesson);setView('learn');setQuery('');window.scrollTo({top:0,behavior:'smooth'})};
  const jump=id=>{setCurrentLesson(id.startsWith('intro-')?'intro':'pv');setView('learn');setQuery('');setTimeout(()=>document.getElementById(id)?.scrollIntoView({behavior:'smooth',block:'start'}),0)};
  const go=v=>{setView(v);setQuery('');window.scrollTo({top:0,behavior:'smooth'})};
  return <div className="app"><header className="topbar"><button className="brand" aria-label="Finance Theory I home" onClick={()=>go('learn')}><Icon name="book"/> <span>Finance Theory I</span></button><nav><button className={view==='learn'?'active':''} onClick={()=>go('learn')}>Learn</button><button className={view==='modules'?'active':''} onClick={()=>go('modules')}>Modules</button><button className={view==='library'?'active':''} onClick={()=>go('library')}>Library</button></nav><div className="tools"><label className="search"><Icon name="search"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search" aria-label="Search course"/></label><button aria-label="Open notes" onClick={()=>setNotesOpen(true)}><Icon name="note"/></button></div>{results.length>0&&<div className="search-results">{results.map((r,i)=><button key={i} onClick={()=>r.id?jump(r.id):go('modules')}><span>{r.number}</span>{r.title}</button>)}</div>}</header>
    {view==='learn'&&<div className="lesson-navigation"><div className="lesson-switcher"><button className={currentLesson==='intro'?'active':''} onClick={()=>openLesson('intro')}>01 Introduction</button><button className={currentLesson==='pv'?'active':''} onClick={()=>openLesson('pv')}>02 Present Value</button></div><nav className="progress-rail" aria-label={`${currentLesson==='intro'?'Introduction':'Present Value'} lesson sections`}>{(currentLesson==='intro'?introSections:lessons).map(l=><button onClick={()=>jump(l.id)} key={l.id} title={l.title}><span className="sr-only">{l.title}</span></button>)}</nav></div>}
    {view==='learn'&&(currentLesson==='intro'?<IntroLesson progress={progress} setProgress={setProgress} onOpenSources={()=>setSourcesOpen(true)} onNext={()=>openLesson('pv')}/>:<Lesson progress={progress} setProgress={setProgress} onOpenSources={()=>setSourcesOpen(true)}/>)} {view==='modules'&&<Modules onOpen={openLesson}/>} {view==='library'&&<Library/>}
    <SourceDrawer open={sourcesOpen} onClose={()=>setSourcesOpen(false)} items={currentLesson==='intro'?introSources:sources}/>{notesOpen&&<Notes key={currentLesson} onClose={()=>setNotesOpen(false)} storageKey={currentLesson==='intro'?'finance-notes-intro':'finance-notes-pv'} title={currentLesson==='intro'?'Introduction':'Present Value'}/>} {(sourcesOpen||notesOpen)&&<button className="backdrop" onClick={()=>{setSourcesOpen(false);setNotesOpen(false)}} aria-label="Close drawer"/>}
  </div>
}

createRoot(document.getElementById('root')).render(<React.StrictMode><App/></React.StrictMode>);
