import { createServer } from 'node:http';
import { createReadStream, statSync } from 'node:fs';
import { extname, join, normalize, resolve } from 'node:path';
const port=Number(process.argv[2]||4173),root=process.cwd();
const types={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.json':'application/json','.pdf':'application/pdf','.vtt':'text/vtt; charset=utf-8','.mp4':'video/mp4','.ttf':'font/ttf'};
const send=(res,code,message)=>{res.writeHead(code,{'Content-Type':'text/plain; charset=utf-8'});res.end(message)};
const safe=(base,url)=>{const basePath=resolve(root,base),rel=normalize(decodeURIComponent(url.split('?')[0])).replace(/^[/\\]+/,'');const file=resolve(basePath,rel);if(file!==basePath&&!file.startsWith(basePath+'/'))throw new Error('outside root');return file};
const stream=(req,res,file)=>{let size;try{const stat=statSync(file);if(!stat.isFile())return send(res,404,'Not found');size=stat.size}catch{return send(res,404,'Not found')}res.setHeader('Content-Type',types[extname(file)]||'application/octet-stream');res.setHeader('Accept-Ranges','bytes');let start=0,end=size-1,status=200;if(req.headers.range){const m=/^bytes=(\d+)-(\d*)$/.exec(req.headers.range);if(!m)return send(res,416,'Invalid range');start=Number(m[1]);end=m[2]?Number(m[2]):end;if(start>end||start>=size||end>=size)return send(res,416,'Range not satisfiable');status=206;res.setHeader('Content-Range','bytes '+start+'-'+end+'/'+size)}res.writeHead(status,{'Content-Length':end-start+1});const body=createReadStream(file,{start,end});body.on('error',()=>res.destroy());body.pipe(res)};
createServer((req,res)=>{let url;try{url=req.url||'/';decodeURIComponent(url)}catch{return send(res,400,'Malformed URL')}const asset=url.startsWith('/sources/')||url.startsWith('/media/');let file;try{file=safe(asset?'public':'dist',asset?url:(url==='/'?'index.html':url))}catch{return send(res,400,'Invalid path')}try{if(statSync(file).isFile())return stream(req,res,file)}catch{}if(asset)return send(res,404,'Asset not found');stream(req,res,join(root,'dist/index.html'))}).listen(port,'127.0.0.1',()=>console.log('Finance Theory I: http://127.0.0.1:'+port));
